### ISSUE TITLE
Unpublished posts visible in the series

### ISSUE THREAD

**Issue by SiR-DanieL** [mikejolley/wp-post-series#17]
If a post that is still not published is assigned to a series it will be visible in the list but not clickable. It would be better to not show it at all.

**Comment by Geneus** [comment]
The whole point of a series is to create a collection of items that thematically share the same properties. Showing a scheduled post creates anticipation and informs the reader of upcoming posts in the series. If it didn't display scheduled posts, it would appear as though there is only one post when you start publishing a series, which is counter to what a series is. Displaying it assures the reader that there are upcoming posts in the series and that they can read them once they are published, with the date conveniently appended to the scheduled post. 

For your needs I think it's best you schedule your post then assign it to a series once it has been published. Alternatively, assign it to a series prior to publishing, but I understand how that would invalidate your wanting to schedule the post. 

I don't think @mikejolley is going to change this as this is how scheduled posts are displayed in WordPress. 

Hope that helps!

**Comment by SiR-DanieL** [comment]
@Geneus he changed it already by adding the publishing date to the scheduled post.
