### ISSUE TITLE
creates php error when the_content filter is used outside of posts

### ISSUE THREAD

**Issue by BinaryMoon** [mikejolley/wp-post-series#18]
If the content is used outside of the loop - to filter text in plugins/ widgets/ whatever - the plugin creates a php error.

The problem happens in the add_series_to_content method where it's checking the global $post variable - which is null since the content isn't in the loop.

To fix locally I changed line 219 to this:

```
if ( empty( $post ) || 'post' !== $post->post_type || ! is_main_query() ) {
```

**Comment by jeromeip** [comment]
I can confirm the issue reported here by @BinaryMoon 
I noticed the php notice was triggered during an ajax call on the front side.
My suggestion for fixing is slightly different but I'm not 100% sure it's effective in every condition (on my website, it works fine)
`		if ( ! is_main_query() || 'post' !== $post->post_type ) {`
(I suppose that _post_ will be set if in main query.

**Comment by jeromeip** [comment]
My bad! There are still some situations were my fix is insufficient, so let's stick to @BinaryMoon proposal!
