### ISSUE TITLE
No more shortcodes?

### ISSUE THREAD

**Issue by codeclinic** [mikejolley/wp-post-series#23]
Was the option to add it via shortcode removed?

Any page builder other Gutenberg can only make use of this plugin via shortcodes. That's exactly how I was using it until the current version when shortcodes were apparently removed.

Is there any chance that shortcodes could be reinstated?

Thanks

**Comment by mikejolley** [comment]
@codeclinic There was never a shortcode! It was automatically prepended to the post, and this still happens. The Blocks are optional. If a block is found, content is not prepended. Otherwise, it still is.
