### ISSUE TITLE
French translation not working after using the POT file

### ISSUE THREAD

**Issue by KHannibal** [mikejolley/wp-post-series#8]
Hi Mike,

Thank you for your plugin, it's really nice and easy to use. I've been translating a few themes and plugins for a few years and I've decided to translate your plugin into French. However, despite creating the fr_FR.po and .mo files by using the POT file you made available, the plugin keeps being stuck in English. The two .po and .mo files have been uploaded to the "languages" folder.

Am I doing something wrong ? Below is the content of the .po file (it's still a draft). I've used Poedit to create it.

Bests,

K

msgid ""
msgstr ""
"Project-Id-Version: WP Post Series 1.1.0\n"
"Report-Msgid-Bugs-To: http://wordpress.org/tag/wp-post-series\n"
"POT-Creation-Date: 2015-12-03 14:18+0100\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2015-12-03 14:26+0100\n"
"Language-Team: \n"
"X-Generator: Poedit 1.8.6\n"
"Last-Translator: \n"
"X-Poedit-Basepath: .\n"
"X-Poedit-KeywordsList: __;_e;_x\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPath-1: ..\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"Language: fr_FR\n"

#: ../templates/series-box.php:9
msgid "This is post #%d of %d in the series <em>&ldquo;%s&rdquo;</em>"
msgstr ""
"Cet article est le n° #%d sur %d dans la série <em>&ldquo;%s&rdquo;</em>."

#: ../wp-post-series.php:57 wp-post-series.php:58
msgid "Post series"
msgstr "Série d’articles"

#: ../wp-post-series.php:66 wp-post-series.php:160
msgid "Series"
msgstr "Série"

#: ../wp-post-series.php:69
msgid "Search %s"
msgstr "Rechercher %s"

#: ../wp-post-series.php:70
msgid "All %s"
msgstr "Tous les %s"

#: ../wp-post-series.php:71
msgid "%s"
msgstr "%s"

#: ../wp-post-series.php:72
msgid "%s:"
msgstr "%s :"

#: ../wp-post-series.php:73
msgid "Edit %s"
msgstr "Modifier %s"

#: ../wp-post-series.php:74
msgid "Update %s"
msgstr "Mettre à jour %s"

#: ../wp-post-series.php:75
msgid "Add New %s"
msgstr "Ajouter une nouvelle %s"

#: ../wp-post-series.php:76
msgid "New %s Name"
msgstr "Nouveau nom de %s"

#: ../wp-post-series.php:180
msgid "N/A"
msgstr "N/A"

#: ../wp-post-series.php:203
msgid "Show all series"
msgstr "Montrer toutes les séries d’articles"

#. Plugin Name of the plugin/theme
msgid "WP Post Series"
msgstr "WP Post Series"

#. Plugin URI of the plugin/theme
msgid "https://github.com/mikejolley/wp-post-series"
msgstr "https://github.com/mikejolley/wp-post-series"

#. Description of the plugin/theme
msgid ""
"Lets you setup a simple series of posts using taxonomies. Posts within a "
"series will show an information box above the content automatically with "
"links to other posts in the series and a description."
msgstr ""
"Permet de créer simplement une série d’articles en utilisant les "
"taxonomies. Les articles d’une série afficheront automatiquement une "
"boîte d’information au-dessus du contenu avec des liens vers les autres "
"articles de la séries ainsi qu’une description."

#. Author of the plugin/theme
msgid "Mike Jolley"
msgstr "Mike Jolley"

#. Author URI of the plugin/theme
msgid "http://mikejolley.com"
msgstr "http://mikejolley.com"

**Comment by jeromeip** [comment]
@KHannibal Funny! I was just having the same issue, working also on fr_FR translation. Please find for your information my draft-as-well translation. 

[wp-post-series-fr_FR.po.txt](https://github.com/mikejolley/wp-post-series/files/51449/wp-post-series-fr_FR.po.txt)

**Comment by KHannibal** [comment]
Thank you @jeromeip ! Once we know what's wrong with the translation, shall we "merge" our translation files in order to have the most perfect translation ever ? ;)

**Comment by dominicpratt** [comment]
+1

Just translated the .pot-file into german, but the new translation is not used by the plugin.

[de_DE.po.txt](https://github.com/mikejolley/wp-post-series/files/73396/de_DE.po.txt)

**Comment by mikejolley** [comment]
Move translations over to https://translate.wordpress.org/projects/wp-plugins/wp-post-series. There may be an issue with your MO file, but using translate.wordpress will do it all for you (and download the po/mo automatically with the plugin if its at 100%).

**Comment by jeromeip** [comment]
@KHannibal (Sorry for this late reply) Feel free to look at my translations for possibly enhance yours!
